apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3  # 배포할 포드의 개수
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: goodacr.azurecr.io/kwujio/front:latest  # ACR에 올린 이미지 경로와 태그를 지정
          ports:
            - containerPort: 8080
